# Generated by Django 5.1.7 on 2026-04-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_email_sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
