# Generated by Django 5.1.7 on 2026-04-14 10:32

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('last_page', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_english', models.CharField(max_length=255)),
                ('baab_name_urdu', models.CharField(max_length=255)),
                ('baab_name_english', models.CharField(blank=True, max_length=255, null=True)),
                ('start_hadith_number', models.IntegerField()),
                ('end_hadith_number', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baabs', to='hadith.book')),
            ],
        ),
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_english', models.CharField(max_length=255)),
                ('chapter_arabic', models.CharField(blank=True, max_length=255, null=True)),
                ('chapter_urdu', models.CharField(blank=True, max_length=255, null=True)),
                ('hadith_number', models.IntegerField()),
                ('arabic_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('english_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('urdu_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hadiths', to='hadith.baab')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadiths', to='hadith.book')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['book__order', 'hadith_number'],
                'constraints': [models.UniqueConstraint(fields=('book', 'hadith_number'), name='unique_hadith_per_book')],
            },
        ),
    ]
