# Generated by Django 5.1.7 on 2026-04-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hadith',
            options={},
        ),
    ]
