# Generated by Django 5.1.7 on 2026-04-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0002_alter_hadith_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hadith',
            options={'ordering': ['book__order', 'chapter_number', 'hadith_number']},
        ),
        migrations.AddField(
            model_name='hadith',
            name='chapter_number',
            field=models.IntegerField(default=0),
        ),
    ]
