# Generated by Django 5.1.7 on 2026-04-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0003_alter_hadith_options_hadith_chapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadith',
            name='chapter_hadith_id',
            field=models.IntegerField(default=0),
        ),
    ]
