# Generated by Django 5.1.7 on 2026-04-27 10:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0006_normalize_hadith_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith',
            name='reference',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
