# Generated by Django 5.1.7 on 2026-06-10 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0007_alter_hadith_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField()),
                ('chapter_english', models.CharField(max_length=255)),
                ('chapter_arabic', models.CharField(blank=True, max_length=255, null=True)),
                ('chapter_urdu', models.CharField(blank=True, max_length=255, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='hadith.book')),
            ],
            options={
                'ordering': ['chapter_number'],
                'unique_together': {('book', 'chapter_number')},
            },
        ),
        migrations.AddField(
            model_name='baab',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baabs', to='hadith.chapter'),
        ),
    ]
