# Generated by Django 5.1.7 on 2026-06-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0008_chapter_baab_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadith',
            name='status',
            field=models.CharField(blank=True, choices=[('Sahih', 'Sahih'), ('Hasan', 'Hasan'), ('Daif', "Da'if"), ('Maudu', "Maudu'"), ('Marfu', "Marfu'"), ('Mawquf', 'Mawquf'), ('Maqtu', "Maqtu'"), ('Mutawatir', 'Mutawatir'), ('Ahad', 'Ahad')], max_length=20, null=True),
        ),
    ]
