# Generated by Django 5.1.7 on 2026-06-13 03:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0009_hadith_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadith',
            name='detailed_explanation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
