# Generated by Django 5.1.7 on 2026-06-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0010_hadith_detailed_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HadithDocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='hadith_uploads/', verbose_name='Word Document (.docx)')),
                ('result_log', models.TextField(blank=True, editable=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Upload Word Document',
                'verbose_name_plural': 'Upload Word Document',
            },
        ),
    ]
