# Generated by Django 5.1.7 on 2026-04-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_split',
            field=models.BooleanField(default=False, verbose_name='pages split'),
        ),
        migrations.AddField(
            model_name='book',
            name='total_pages',
            field=models.PositiveIntegerField(default=0, verbose_name='total pages'),
        ),
    ]
