# Generated by Django 5.1.7 on 2026-04-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_is_split_book_total_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='download count'),
        ),
        migrations.AddField(
            model_name='book',
            name='read_count',
            field=models.PositiveIntegerField(default=0, verbose_name='read count'),
        ),
    ]
