# Generated by Django 5.1.7 on 2026-04-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_download_count_book_read_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('ocr', 'OCR'), ('html', 'HTML')], default='pdf', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
