# Generated by Django 5.1.7 on 2026-06-10 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_userbookdownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSessionDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_downloads', to='books.book')),
            ],
            options={
                'db_table': 'book_session_downloads',
                'unique_together': {('session_key', 'book')},
            },
        ),
        migrations.CreateModel(
            name='BookSessionRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reads', to='books.book')),
            ],
            options={
                'db_table': 'book_session_reads',
                'unique_together': {('session_key', 'book')},
            },
        ),
    ]
