# Generated by Django 5.1.7 on 2026-04-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_category_question_category_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_essential',
            field=models.BooleanField(default=False),
        ),
    ]
