# Generated by Django 5.1.7 on 2026-04-17 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_answer_is_essential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_essential',
        ),
    ]
