# Generated by Django 5.1.7 on 2026-06-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0008_alter_question_options_question_is_most_read_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
    ]
