# Generated by Django 5.1.7 on 2026-06-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0009_alter_ordering_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
