# Generated by Django 5.1.7 on 2026-06-09 23:12

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', validators=[blog.models.validate_blog_cover_image]),
        ),
    ]
