# Generated by Django 5.1.7 on 2026-04-06 09:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masail',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content'),
        ),
    ]
